# dataset_path: /media/mnt2/nuscenes-lidarseg
dataset_path: /media/mnt3/nuScenes

labels:
  0: 'noise'
  1: 'animal'
  2: 'human.pedestrian.adult'
  3: 'human.pedestrian.child'
  4: 'human.pedestrian.construction_worker'
  5: 'human.pedestrian.personal_mobility'
  6: 'human.pedestrian.police_officer'
  7: 'human.pedestrian.stroller'
  8: 'human.pedestrian.wheelchair'
  9: 'movable_object.barrier'
  10: 'movable_object.debris'
  11: 'movable_object.pushable_pullable'
  12: 'movable_object.trafficcone'
  13: 'static_object.bicycle_rack'
  14: 'vehicle.bicycle'
  15: 'vehicle.bus.bendy'
  16: 'vehicle.bus.rigid'
  17: 'vehicle.car'
  18: 'vehicle.construction'
  19: 'vehicle.emergency.ambulance'
  20: 'vehicle.emergency.police'
  21: 'vehicle.motorcycle'
  22: 'vehicle.trailer'
  23: 'vehicle.truck'
  24: 'flat.driveable_surface'
  25: 'flat.other'
  26: 'flat.sidewalk'
  27: 'flat.terrain'
  28: 'static.manmade'
  29: 'static.other'
  30: 'static.vegetation'
  31: 'vehicle.ego'
labels_16:
  0: 'noise'
  1: 'barrier'
  2: 'bicycle'
  3: 'bus'
  4: 'car'
  5: 'construction_vehicle'
  6: 'motorcycle'
  7: 'pedestrian'
  8: 'traffic_cone'
  9: 'trailer'
  10: 'truck'
  11: 'driveable_surface'
  12: 'other_flat'
  13: 'sidewalk'
  14: 'terrain'
  15: 'manmade'
  16: 'vegetation'
learning_map:
  1: -1
  5: -1
  7: -1
  8: -1
  10: -1
  11: -1
  13: -1
  19: -1
  20: -1
  0: -1
  29: -1
  31: -1
  9: 0
  14: 1
  15: 2
  16: 2
  17: 3
  18: 4
  21: 5
  2: 6
  3: 6
  4: 6
  6: 6
  12: 7
  22: 8
  23: 9
  24: 10
  25: 11
  26: 12
  27: 13
  28: 14
  30: 15
learning_map_inv:
  -1: 0 # noise 
  0: 9 # barrier 
  1: 14 # bicycle
  2: 16 # bus
  3: 17 # 
  4: 18 #
  5: 21 #
  6: 2  #
  7: 12 #
  8: 22 # trailer 
  9: 23 # truck
  10: 24 #
  11: 25 #
  12: 26 #
  13: 27 #
  14: 28 # 
  15: 30 #

color_map:  # BGR format
  0: [0, 0, 255]       # barrier - red
  1: [255, 0, 0]       # bicycle - blue
  2: [255, 128, 0]     # bus - orange
  3: [0, 255, 0]       # car - green
  4: [0, 128, 255]     # construction_vehicle - light orange
  5: [255, 0, 255]     # motorcycle - magenta
  6: [153, 0, 153]     # pedestrian - purple
  7: [0, 255, 255]     # traffic_cone - yellow
  8: [128, 0, 255]     # trailer - violet
  9: [0, 102, 204]     # truck - dark blue
  10: [128, 128, 128]  # driveable_surface - gray
  11: [128, 64, 0]     # other_flat - brown
  12: [192, 192, 0]    # sidewalk - olive
  13: [0, 128, 128]    # terrain - teal
  14: [0, 0, 128]      # manmade - navy
  15: [0, 255, 128]    # vegetation - mint green